server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/identity_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:bookland123}

jwt:
  signer-key: ${JWT_SIGNER_KEY:1234567890123456789012345678901234567890123456789012345678901234}
  valid-duration: ${JWT_VALID_DURATION:3600}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:604800}

app:
  services:
    user: http://${USER_SERVICE_HOST:localhost}:8082