apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: transcripthub
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: yourusername/transcripthub-users:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Running Database Migrations..."
          until npx prisma migrate deploy; do
            echo "Retrying migration in 5 seconds..."
            sleep 5
          done
          echo "Migration completed successfully."
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: transcripthub-config
              key: DATABASE_HOST
        - name: database-password
          valueFrom:
            secretKeyRef:
              name: transcripthub-secrets
              key: database-password
        - name: DATABASE_URL
          value: "postgresql://postgres:$(database-password)@$(DATABASE_HOST):5432/transcripthub"
      restartPolicy: OnFailure
