server:
  port: 8084

spring:
  application:
    name: meeting-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meeting_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: disabled
      password: disabled

app:
  services:
    file: http://${FILE_SERVICE_HOST:localhost}:8083
    user: http://${USER_SERVICE_HOST:localhost}:8082
